### teste delogin
POST http://localhost:40000/Login HTTP/1.1
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzQ3ODI5NzksInVzZXJuYW1lIjoicXdlIn0.SlYYCm8J6wlpb3i1jJcSvhSz6VjwKvzPOxza8P6-hzo

{    
    "UserName": "qwe",
    "Password": "qwe"
}

### teste de logout
POST http://localhost:40000/Logout HTTP/1.1
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzQ3ODI5NzksInVzZXJuYW1lIjoicXdlIn0.SlYYCm8J6wlpb3i1jJcSvhSz6VjwKvzPOxza8P6-hzo

{    
  
}

### teste de getAllAlunos
POST http://localhost:40000/getAlunoByID HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTc1ODAyMDkzOCwiZXhwIjoxNzU4MDI4MTM4fQ.PZyn9B9u44qVjNM6XOxSTVlai2aBiDu0u5tpsL2JgK4

{    
    "ID": 1
}